name: "Changelog"
description: "Generate and commit CHANGELOG.md"
inputs:
  token:
    description: Personal access token
    default: ${{ github.token }}
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}
        fetch-depth: 0
    - name: Set up the Git client
      run: |
        git config --global user.name 'Github Actions'
        git config --global user.email 'github-actions@github.com'
      shell: bash
    - name: Create the changelog
      run: |
        curl -sSfL https://raw.githubusercontent.com/nbycomp/ory-github-actions/nbycomp/changelog/create_changelog.sh | bash
      shell: bash
    - name: Check if CHANGELOG.md was modified
      id: check_changelog
      run: |
        if git status --short | grep -q 'CHANGELOG.md'; then
          echo "CHANGELOG modified" && echo "CHANGELOG_MODIFIED=true" >> $GITHUB_OUTPUT;
        fi
      shell: bash
    - name: Commit the changes
      if: ${{ steps.check_changelog.outputs.CHANGELOG_MODIFIED == 'true' }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        branch="$(date +%s)"
        git checkout -b "$branch" || true
        git add CHANGELOG.md || true
        git commit -m "ci(docs): Update changelog" || true
        git pull origin master --rebase || true
        git push origin HEAD:master
      shell: bash
